language: node_js
node_js:
    - stable

env:
    global:
        - DISPLAY=":99.0"

matrix:
    include:
        - env: FF_REQUIRED=38.0.1esr
          addons:
              firefox: 38.0.1esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=45.9.0esr
          addons:
              firefox: 45.9.0esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.0esr
          addons:
              firefox: 52.0esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.0.1esr
          addons:
              firefox: 52.0.1esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.0.2esr
          addons:
              firefox: 52.0.2esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.1.0esr
          addons:
              firefox: 52.1.0esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.1.1esr
          addons:
              firefox: 52.1.1esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.1.2esr
          addons:
              firefox: 52.1.2esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=52.2.0esr
          addons:
              firefox: 52.2.0esr
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=54.0
          addons:
              firefox: 54.0
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils
        - env: FF_REQUIRED=latest
          addons:
              firefox: latest
              apt:
                  packages:
                      - ca-certificates
                      - poppler-utils

before_install:
    - sh -e /etc/init.d/xvfb start
    - npm install -g jpm

before_script:
    - export FFBIN="$(which firefox)"
    - cp docker/root/etc/firefox-esr/cmdlnprint.js $(dirname ${FFBIN})/defaults/pref/cmdlnprint.js
    - jpm --version
    - which pdftotext && which firefox && firefox -version

script:
    - jpm xpi -v --addon-dir src/ --dest-dir .
    - unzip -l cmdlnprint.xpi
    - jpm run -v --addon-dir src/ --binary "${FFBIN}" --binary-args '-print src/test/assets/sample.html -print-mode pdf -print-file /tmp/output.pdf'
    - ls -alh /tmp/output.pdf
    - pdftotext -q -raw -enc Latin1 -nopgbrk /tmp/output.pdf - | tee /tmp/output.txt
    - diff -b -B src/test/assets/expected-output.txt /tmp/output.txt || true
